### ISSUE TITLE
On Raspi settings tab crashes

### ISSUE THREAD

**Issue by beniroquai** [openUC2/imswitch-aiortc-react#1]
Loading internal plugin "Jupyter-Engine-Manager"...
default_base_frame.html?version=0.5.9&id=Jupyter-Engine-Manager_vxi0g1727092596308:32 Service worker (core) was activated.
connection.js:22 connection to the imjoy-rpc peer mg2hkwxysi1727092596596 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for Jupyter-Engine-Manager
main.js:193 ImJoy RPC loaded successfully!
jailedPlugin.js:800 Plugin Jupyter-Engine-Manager_vxi0g1727092596308: Jupyter Engine Manager initialized
pluginManager.js:1001 Jupyter-Engine-Manager plugin loaded.
pluginManager.js:992 Loading internal plugin "WebPythonWorker"...
default_base_frame.html?version=0.5.9&id=WebPythonWorker_5bv621727092597091:32 Service worker (core) was activated.
imjoyLoader.js:155 Using cached imjoy-rpc library v0.5.9.
connection.js:22 connection to the imjoy-rpc peer mwroj5bdoa1727092597377 is limited to origin https://lib.imjoy.io.
jailedPlugin.js:388 loaded imjoy-rpc v0.5.9 for WebPythonWorker
main.js:193 ImJoy RPC loaded successfully!
pluginManager.js:1001 WebPythonWorker plugin loaded.
imjoyBasicApp.js:104 ImJoy Core started successfully!
Modal.vue:236 Modal "window-modal-dialog" has scrollable flag set to true but height is not "auto" (500px)
beforeMount @ Modal.vue:236
He @ vue.min.js:6
Yt @ vue.min.js:6
(anonymous) @ vue.min.js:6
wn.$mount @ vue.min.js:6
wn.$mount @ vue.min.js:6
init @ vue.min.js:6
(anonymous) @ vue.min.js:6
f @ vue.min.js:6
h @ vue.min.js:6
f @ vue.min.js:6
(anonymous) @ vue.min.js:6
e._update @ vue.min.js:6
r @ vue.min.js:6
fn.get @ vue.min.js:6
fn @ vue.min.js:6
(anonymous) @ vue.min.js:6
wn.$mount @ vue.min.js:6
wn.$mount @ vue.min.js:6
t._init @ vue.min.js:6
wn @ vue.min.js:6
loadImJoyBasicApp @ imjoyBasicApp.js:196
await in loadImJoyBasicApp (async)
(anonymous) @ Tab_LiveView.js:80
p @ regeneratorRuntime.js:45
(anonymous) @ regeneratorRuntime.js:133
(anonymous) @ regeneratorRuntime.js:74
i @ asyncToGenerator.js:3
l @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ Tab_LiveView.js:79
load (async)
(anonymous) @ Tab_LiveView.js:113
os @ react-dom.production.min.js:244
ku @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
w @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 12 more frames
Show less
MCTController.js:65 {isMCTrunning: false, nImagesTaken: 0, timePeriod: 60, zStackEnabled: false, zStackMin: 0, …}
MCTController.js:65 {isMCTrunning: false, nImagesTaken: 0, timePeriod: 60, zStackEnabled: false, zStackMin: 0, …}
HistoScanController.js:95 
        
        
       GET https://0.0.0.0:8001/HistoScanController/getHistoStatus 404 (Not Found)
(anonymous) @ HistoScanController.js:95
setInterval (async)
(anonymous) @ HistoScanController.js:93
os @ react-dom.production.min.js:244
ku @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:283
wu @ react-dom.production.min.js:281
uu @ react-dom.production.min.js:273
Vo @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 7 more frames
Show less
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading '0')
    at mp (HistoScanController.js:294:26)
    at Zi (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:197:258)
    at Zs (react-dom.production.min.js:292:88)
    at xu (react-dom.production.min.js:280:389)
    at bu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at au (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
fl @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
_a @ react-dom.production.min.js:144
Ss @ react-dom.production.min.js:262
xs @ react-dom.production.min.js:260
ys @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
wu @ react-dom.production.min.js:281
au @ react-dom.production.min.js:270
w @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 11 more frames
Show less
HistoScanController.js:294 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at mp (HistoScanController.js:294:26)
    at Zi (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:197:258)
    at Zs (react-dom.production.min.js:292:88)
    at xu (react-dom.production.min.js:280:389)
    at bu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at au (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
mp @ HistoScanController.js:294
Zi @ react-dom.production.min.js:167
El @ react-dom.production.min.js:197
Zs @ react-dom.production.min.js:292
xu @ react-dom.production.min.js:280
bu @ react-dom.production.min.js:280
gu @ react-dom.production.min.js:280
iu @ react-dom.production.min.js:271
au @ react-dom.production.min.js:268
w @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 10 more frames
Show less

@beniroquai

**Comment by beniroquai** [comment]
activating histocontroller sovles it partially
